### ISSUE TITLE
JqInputMask attached to DateField or PopupDateField all field events silent and cannot fire.

### ISSUE THREAD

**Issue by blueiceprj** [wbstr/vaadin-jqinputmask#1]
JqInputMask attached to DateField or PopupDateField all field events silent and cannot fire.

Example (this is extended DateField)

```
        addValueChangeListener(event -> {
            final Object val = event.getProperty().getValue();
            .....
        });

JqInputMask.date(this, this.mask).apply();

```

**Comment by kumm** [comment]
what do you mean 'all field events' ? 
I can reproduce change event problem, but other events seem to work.

**Comment by blueiceprj** [comment]
Hi,

'all field events' mean that , all field events binded from vaadin core framework or after I added valuechange event in my code. Did you try with PopupDateField? When you input value with textfield in popupdatefield, than field value will cannot change.  There is a problem popupdatefield when used JqInputMask. For example. Write to textfield area in popupfield with masked. Than open the popup for select and look at the selected date value. You can see selected date value,  different your input textfield value.

As a result , I think that, in popupdatefield text input area events (change value etc.) blocking from JqInputMask extension.

Thanks.

**Comment by kumm** [comment]
Please try it with current HEAD.

**Comment by blueiceprj** [comment]
Sorry. Nothing changed.

**Comment by kumm** [comment]
Take a try again.
It works now really in the demo project.

**Comment by blueiceprj** [comment]
Thanks
Great job. It is working.
